### ISSUE TITLE
Яндекс.Практикум:Код-ревью.

### ISSUE THREAD

**Issue by zlocate** [Atm0Sphere94/project14#1]
Добрый вечер

**Необходимо исправить** ревью проходит в рамках PR, поэтому крайне важно чтобы ревьювер имел возможность изучить PR содержащий все изменения в рамках работы над задачей данного спринта. Также это позволяет прослеживать историю изменений и нить обсуждения между студентом и ревьювером.
Пожалуйста, обратите на это внимание.

**Comment by zlocate** [comment]
Пожалуйста не удаляйте репозиторий и\или не злоупотребляете перезаписью истории коммитов форс-пушем. При командной работе это приведет к крайне неприятным конфликтом расхождения истории коммитов из-за чего слить ваши и, например, трех других коллег, правки будет непросто :)

**Comment by zlocate** [comment]
**Нужно исправить** присутствуют ошибки линтинга (в т.ч в файле конфигурации линтера)
```
/home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/.eslintrc.js
  2:1   error  Expected indentation of 2 spaces but found 4   indent
  2:5   error  Unnecessarily quoted property 'extends' found  quote-props
  2:5   error  Strings must use singlequote                   quotes
  2:16  error  Strings must use singlequote                   quotes
  3:1   error  Expected indentation of 2 spaces but found 4   indent
  3:5   error  Unnecessarily quoted property 'rules' found    quote-props
  3:5   error  Strings must use singlequote                   quotes
  4:1   error  Expected indentation of 4 spaces but found 6   indent
  4:7   error  Strings must use singlequote                   quotes
  4:32  error  Strings must use singlequote                   quotes
  4:43  error  Unnecessarily quoted property 'allow' found    quote-props
  4:43  error  Strings must use singlequote                   quotes
  4:53  error  Strings must use singlequote                   quotes
  4:62  error  Missing trailing comma                         comma-dangle
  5:1   error  Expected indentation of 2 spaces but found 4   indent
  5:6   error  Missing trailing comma                         comma-dangle
  6:1   error  Expected indentation of 0 spaces but found 2   indent
  6:5   error  Newline required at end of file but not found  eol-last

/home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/routes/routes.js
  9:18  error  'req' is defined but never used  no-unused-vars
  9:23  error  'res' is defined but never used  no-unused-vars
```

Те из них, что вы считаете ложным срабатыванием необходимо погасить при помощи игнор-комментариев
https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by zlocate** [comment]
**Нужно исправить** при попытке зарегистрировать 2 учетные записи на один email сервис возвращает неинформативную ошибку со статус-кодом 500 вместо соответствующей ошибки со статус-кодом 409 ("Данный email уже занят" или как-то так)

**Comment by Atm0Sphere94** [comment]
"Пожалуйста не удаляйте репозиторий и\или не злоупотребляете перезаписью истории коммитов форс-пушем. " Денис простите пожалуйста! С этим проектом у меня как то не заладилось с ГИТом, я прошу прощения и буду исправляться!

**Comment by zlocate** [comment]
Благодарю за понимание :)

**Comment by Atm0Sphere94** [comment]
Насчет линтинга - в данный момент он молчит. Проверяю конфигурацию=) Кстати данную редакцию конфига для линтера посоветовал прошлый ревьювер с пометкой для бэкэнда этого достаточно, прокомментируй пожалуйста!

**Comment by zlocate** [comment]
**Нужно исправить** при попытке зарегистрировать пользователя с неполными данными (например без указания `password` или `about`) сервис возвращает 500ю ошибку вместо ошибки валидации со статус-кодом 400.
http://i.imgur.com/KM5PWr8.png

**Comment by zlocate** [comment]
Текущий конфиг минималистично-достаточный. Но линтер каждый хороший программист настраивает под себя и под конкретный проект.
При правильной настройке он может творить "магию" и предупреждать об огромном числе потенциальных проблем.
В целом базовый конфиг airbnb ок.

Наша же ситуация вызвана вероятно не только и не столько самим конфигом сколько командой при помощи которой мы запускаем проверку.
(Т.к я ревьювлю и вебпак спринт и не могу быть уверен что студенты заполняют .gitignore\.eslintignore коррректно то использую игнор-флаги прямо в команде)
З.Ы eslint при этом у меня устанолен глобально при помощи `npm i -g eslint`

Сама команда (сделал ее алиасом lint у себя в командном интерпретаторе)
`eslint --ignore-pattern 'node_modules' --ignore-pattern 'public' --ignore-pattern 'dist' -c .eslintrc* --ext .js .`

**Comment by zlocate** [comment]
**Нужно исправить** авторизация работает некорректно. Если введен корректный логин (почта) то корректность пароля не проверяется.
Скриншот проблемы: http://i.imgur.com/4GYcLJQ.png

Проблема связана с тем, что метод findUserByEmail асинхронный (как в принципе и почти любой работающий с БД кроме тех что явно заявляют обратное)
Соответственно мы не дожидаемся результата поиска сразу же переходим к генерации токена и возвращаем ответ и только потом вылетает ошибка

UPD: Лечение проблемы - ее следствие - надо дожидаться результатов работы данного метода.
Т.к вы используете async\await то достаточно добавить await перед именем соответствующего метода :)

**Comment by Atm0Sphere94** [comment]
Линтинг в routes.js поправил, линт молчит для eslint.js - https://yadi.sk/i/sJmRiuBZM0GtMw

**Comment by zlocate** [comment]
**Нужно исправить** мидлвара централизованной обработки ошибок (она емнип в 15м спринте появляется, на опережение работаем? :) )
Ожидаем статус-код ответа в поле statusCode а в некоторых ошибках он задан как status из-за чего вместо специфичной ошибки мы всегда получаем 500ю

**Comment by Atm0Sphere94** [comment]
насчет централизованной мидл вары - спасибо предыдущему ревьюверу - который аккуратно написал "можно лучше"

**Comment by zlocate** [comment]
По линтеру чуть позже вернемся. Идем дальше :)

**Comment by Atm0Sphere94** [comment]
СтатусКоды поправил, идем=))))

**Comment by Atm0Sphere94** [comment]
По чек листу специфические ошибки только 401? или опять же "можно лучше"? =)

**Comment by zlocate** [comment]
**Нужно исправить** 
Далеко не уйдем пока. Мидлвара авторизации ожидает токен в req.cookies.jwt.
Для того чтобы это сработало необходимо чтобы куки были корректно распаршены. 
Для этого есть cookies-parser, который необходимо подключить также как и bodyParser.
Сейчас падаем так:
```
TypeError: Cannot read property 'jwt' of undefined
    at auth (/home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/middlewares/auth.js:8:31)
```

**Comment by Atm0Sphere94** [comment]
Денис секунду, можно я запушу последний вариант - кУКПарсер подключен

**Comment by zlocate** [comment]
По поводу кодов ошибок. Ситуация следующая в принципе мы по нарастанию просим обрабатывать сначала 400 и 404, затем 401 и 409.
Строго говоря уже в чек-листе ревьювера для 13го спринта присутствует следующая формулировка
http://i.imgur.com/sVDs24i.png
Трактоваться она может по-разному, но я за то, чтобы отдавать максимально честный и специфичный код ошибки как можно чаще и как можно реше 500й с абстрактным "что-то сломалось".
Особенно это касается финальных работ 14-15 спринта.

**Comment by Atm0Sphere94** [comment]
Тогда конечно все сделаю, запушил вариант с парсером

**Comment by zlocate** [comment]
Ох, не люблю я "быстрофиксы на продакшн" (доброски во время ревью) :)

**Comment by Atm0Sphere94** [comment]
Ну прости, общаться вживую с ревьювером одно удовольствие, это ж экспириенс=)))

**Comment by zlocate** [comment]
**Нужно исправить** при попытке создать карточки с некорректным именем или url сервис возвращает 500ю ошибку вместо 400й и соответствующим текстом ошибки (ошибка валидации, поле такое-то некорректно заполнено (err.message для ValidationError))
http://i.imgur.com/2xFjTr7.png

**Comment by zlocate** [comment]
Поймать ее можно по err.name=='ValidationError' (есть более изящные варианты но пока рановато для них :) )

**Comment by Atm0Sphere94** [comment]
и сразу вопрос, в доке по JWT тамв примерах передача токена в headers а в чатах слака в cookies как быть

**Comment by zlocate** [comment]
**Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400 (ошибка валидации)
Фактически же внутри ее можно поймать как CastError. (err.name='CastError')

Строго говоря эта ошибка может означать не только ошибку приведение строки к ID но пока мы допустим что это так.

Еще можно проверять на валидность "по форме" ObjectId при помощи встроенного монгусовскоого метода, емнип это mongoose.Types.ObjectId.isValid(id)
Могу на память наврать, но направление мысли думаю ясно.

**Comment by zlocate** [comment]
> и сразу вопрос, в доке по JWT тамв примерах передача токена в headers а в чатах слака в cookies как быть

JWT это просто способ stateless авторизации (строго говоря нам не нужен отдельный сервис чтобы хранить соответствие сессия (токен) => пользователь) а токен сам по себе заключает информацию о сессионных данных.
Способ передачи его некритичен.
Часто делают это в заголовках, но способ с куками удобнее для студентов тем что Postman (как и многие другие клиенты) например подхватывает куку и прописывать Bearer токен для каждого запроса для тестирования не нужно :)

**Comment by zlocate** [comment]
**Нужно исправить** можно удалить чужую карточку (нужно проверять что текущий пользователь === owner карточки) 
З.Ы Не забудьте пожалуйста только привести при сравнении это все к строке (студенты часто забывают и проверка фактически не работает ибо буфер сравнивается со строкой, во время реализации поймете о чем я)

**Comment by zlocate** [comment]
**Можно лучше** не искать одну карточку дважды
```
const card = await Card.findById(id);
        if (!card) {
            throw new NotFoundError('Карточка не найдена');
        }
        const cardToDelete = await Card.findByIdAndRemove(id);
```
Cмотрим. Если мы нашли карточку по ID и нам хватает прав на ее удаление то повторно искать ее для удаления уже не нужно.
Можно просто вызвать card.remove() (не забываем что это тоже асинхронная операция которую нужно либо awaitить либо обрабатывать результат в then)

**Comment by Atm0Sphere94** [comment]
Понимаю, отлично! Буду читать! Поймать ее можно по err.name=='ValidationError'  -  нутри ее можно поймать как CastError. (err.name='CastError') - термин поймать пока неясен, можно пример?

**Comment by zlocate** [comment]
.catch((err)=>{
if(err.name==="ValidationError") console.log("Произошла ошибка валидации");
})

Эту проверку можно не дублировать в куче мест а сделать в одном :)
Вопрос насколько это правильно - дискуссионныый но для простоты и в рамках учебного процесса более чем уместно

**Comment by Atm0Sphere94** [comment]
Понял! Сделаем! Ну в смысле позже=) Ревьювер не любит доделок на коленке=)))

**Comment by zlocate** [comment]
**Можно лучше** при выводе списка пользователей мы их каждый раз сортируем по имени.
Оставим вопрос что метод который выводит список без пагинации (возможность вывода постранично с определенным размером окна limit-offset это не решение из реального мира)
Раз уж полезли в дебри отмечу один момент - чтобы делать это эффективно можно строить индекс который будет учитывать эту сортировку.
Тогда операция сортировки будет гораздо дешевле для нас (но да, мы получим микрозадержку при записи на формирование индекса)

https://docs.mongodb.com/manual/tutorial/sort-results-with-indexes/

**Comment by zlocate** [comment]
Эх, надо в наставники переходить. Там хоть формат работы подразумевает возможность индивидуальной работы и поковыраться в дебрях. 
Ревьюверы залимичены чек-листами и временными затратами на проверку работ

**Comment by zlocate** [comment]
**Можно лучше** можно зарегистрировать пользователя с пустым паролем. Фактически валидатор на уровне БД считает длину хэша, который будет нужной длины даже от пустой строки

**Comment by zlocate** [comment]
**Можно лучше** при регистрации пользователя можно пойти другим путем - не указывать какие поля мы конкретно возвращаем а удалять лишние. При помощи оператора delete.
Хотя способ - явно указать возвращаемые значения потенциально безопаснее.

**Comment by Atm0Sphere94** [comment]
> **Можно лучше** можно зарегистрировать пользователя с пустым паролем. Фактически валидатор на уровне БД считает длину хэша, который будет нужной длины даже от пустой строки

А мы же в модели пишем min - max.lengh?

**Comment by zlocate** [comment]
> > **Можно лучше** можно зарегистрировать пользователя с пустым паролем. Фактически валидатор на уровне БД считает длину хэша, который будет нужной длины даже от пустой строки
> 
> А мы же в модели пишем min - max.lengh?
Для других значений это отлично работает. Поскольку мы накладываем ограничения на непосредственно значения, тут же мы в бд же храним хэш от значения. А суть хэша это сжимающиее преобразование дающее от любого размера входа одинакового размера выход. (в зависимости от параметров хэш-функции)

Т.е хоть от пароля 123456789 хоть от пароля 123 хоть от "" хэш будет одинаковой длины

**Comment by zlocate** [comment]
Рекомендация по поводу использованию name может быть опущена, ниже по коду вижу успешное применение instanceOf что более корректно.
```
if (err instanceof mongoose.Error.ValidationError) {
            return next(new BadRequestError(err.message));
        }
```

**Comment by zlocate** [comment]
**Нужно исправить** параметр maxAge для cookie необходимо задавать в виде миллисекунд, сейчас там 7d
Скрин документации разъясняющий данный аспект
http://i.imgur.com/Y8wen6L.png

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** параметр maxAge для cookie необходимо задавать в виде миллисекунд, сейчас там 7d
> Скрин документации разъясняющий данный аспект
> http://i.imgur.com/Y8wen6L.png

'604800'?

**Comment by zlocate** [comment]
Лучше вместо магических констант их как-то обзывать 
`const 7DAYS = x * x * x * x`
Чтобы следующий читающий код не думал, почему именно это число? И когда нужно его менять :D

**Comment by zlocate** [comment]
Саммери: несмотря на, в целом, высокий уровень работы, использование продвнутых фишек языка вроде async\await и общую аккуратность исполнения, текущая реализация требует следующих доработок.

**Нужно исправить** при попытке зарегистрировать 2 учетные записи на один email сервис возвращает неинформативную ошибку со статус-кодом 500 вместо соответствующей ошибки со статус-кодом 409 ("Данный email уже занят" или как-то так)
**Нужно исправить** при попытке зарегистрировать пользователя с неполными данными (например без указания `password` или `about`) сервис возвращает 500ю ошибку вместо ошибки валидации со статус-кодом 400.
http://i.imgur.com/KM5PWr8.png

**Нужно исправить** авторизация работает некорректно. Если введен корректный логин (почта) то корректность пароля не проверяется.
Скриншот проблемы: http://i.imgur.com/4GYcLJQ.png

**Нужно исправить** мидлвара централизованной обработки ошибок (она емнип в 15м спринте появляется, на опережение работаем? :) )
Ожидаем статус-код ответа в поле statusCode а в некоторых ошибках он задан как status из-за чего вместо специфичной ошибки мы всегда получаем 500ю

**Нужно исправить** 
Далеко не уйдем пока. Мидлвара авторизации ожидает токен в req.cookies.jwt.
Для того чтобы это сработало необходимо чтобы куки были корректно распаршены. 
Для этого есть cookies-parser, который необходимо подключить также как и bodyParser.
Сейчас падаем так:
```
TypeError: Cannot read property 'jwt' of undefined
    at auth (/home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/middlewares/auth.js:8:31)
```

**Нужно исправить** при попытке создать карточки с некорректным именем или url сервис возвращает 500ю ошибку вместо 400й и соответствующим текстом ошибки (ошибка валидации, поле такое-то некорректно заполнено (err.message для ValidationError))
http://i.imgur.com/2xFjTr7.png


**Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400 (ошибка валидации)
Фактически же внутри ее можно поймать как CastError. (err.name='CastError')

**Нужно исправить** можно удалить чужую карточку (нужно проверять что текущий пользователь === owner карточки) 

**Нужно исправить** параметр maxAge для cookie необходимо задавать в виде миллисекунд, сейчас там 7d
Скрин документации разъясняющий данный аспект
http://i.imgur.com/Y8wen6L.png

**Comment by zlocate** [comment]
Да, часть из этих ошибок уже исправлены, однако в рамках данной итерации ревью они все же были выявлены. :)

**Comment by Atm0Sphere94** [comment]
Денис, спасибо тебе, за столь развернутое ревью - поработаю поправлю, попрошу вновь посмотреть!

**Comment by zlocate** [comment]
Спасибо. Если будет минутка - после ревью оставьте отзыв о моей проверке. Вам несложно, а мне приятно.
Жду доработок и обсудим реализацию вновь :)

**Comment by Atm0Sphere94** [comment]
> Спасибо. Если будет минутка - после ревью оставьте отзыв о моей проверке. Вам несложно, а мне приятно.
> Жду доработок и обсудим реализацию вновь :)

а где и как отозваться? Я отзовусь=))

**Comment by zlocate** [comment]
> а где и как отозваться? Я отзовусь=)) 

А там в ЛК практикума после проверки дают возможность оценить проверку.
Не знаю дают сразу же или уже после того как работа будет засчитана. Но она есть :)

**Comment by Atm0Sphere94** [comment]
> > а где и как отозваться? Я отзовусь=))
> 
> А там в ЛК практикума после проверки дают возможность оценить проверку.
> Не знаю дают сразу же или уже после того как работа будет засчитана. Но она есть :)

Сделаем, конечно! Спасибо за твой труд!

**Comment by zlocate** [comment]
**Нужно исправить** при попытке запуска сервис падает со следующей ошибкой:

```
Error: Cannot find module '../errors/conflictError'
Require stack:
- /home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/controllers/users.js
```

Причина в том что искомый файл начинается с заглавной буквы.
Просьба также не смешивать различные подходы в именовании сходны сущностей.
Часть файлов, содержащих описание ошибок начинаются с малой буквы, часть с большой, что и приводит к подобным ошибкам.

З.Ы Ну и  IDE обычно подсказывает\подсвечивает такое. Если нет - рекомендую подкрутить настройки, здорово облегчит жизнь.

**Comment by Atm0Sphere94** [comment]
Я одного не могу понять, как у меня Postman вчера вернул 409 ошибку, если модуль потеряляся? Магия=((((

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** при попытке запуска сервис падает со следующей ошибкой:
> 
> ```
> Error: Cannot find module '../errors/conflictError'
> Require stack:
> - /home/console/work/yandex/14/[14] Олег Малышев (m.oleg61@yandex.ru)/controllers/users.js
> ```
> 
> Причина в том что искомый файл начинается с заглавной буквы.
> Просьба также не смешивать различные подходы в именовании сходны сущностей.
> Часть файлов, содержащих описание ошибок начинаются с малой буквы, часть с большой, что и приводит к подобным ошибкам.
> 
> З.Ы Ну и IDE обычно подсказывает\подсвечивает такое. Если нет - рекомендую подкрутить настройки, здорово облегчит жизнь.

Знаю ты не любишь, но я поправил - переименовал =((((

**Comment by Atm0Sphere94** [comment]
IDE обычно подсказывает\подсвечивает такое. Если нет - рекомендую подкрутить настройки, здорово облегчит жизнь. - здесь можно поподробнее (расширения, конфиги и прочая)?

**Comment by zlocate** [comment]
Все зависит от  IDE, которая испоьзуется для разработки.
В целом это базовый функционал.
А так стандартный набор для VS Code: ESLint, Editorconfig Generator, Github PR Request, Beutify, Import Cost, JS Refactor, Node Essentials (гиперпакет, ставит сразу базу необходимого), Path Intelliesence, Node.js Modules Intellisence

**Comment by Atm0Sphere94** [comment]
> Все зависит от IDE, которая испоьзуется для разработки.
> В целом это базовый функционал.
> А так стандартный набор для VS Code: ESLint, Editorconfig Generator, Github PR Request, Beutify, Import Cost, JS Refactor, Node Essentials (гиперпакет, ставит сразу базу необходимого), Path Intelliesence, Node.js Modules Intellisence

Благодарю, поизучаю

**Comment by zlocate** [comment]
**Нужно исправить** в случае если в метод регистрации переданы не все поля, например отсутствует поле password сервис падает в 500ю вместо корректной ValidationError с кодом 400

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** в случае если в метод регистрации переданы не все поля, например отсутствует поле password сервис падает в 500ю вместо корректной ValidationError с кодом 400

Денис а здесь можешь пояснить, ведь мы же в схеме для монго пишем что все поля обязательны, я просто не могу понять где ее лучше отловить, в контроллере создания пользователя по err.name? или как?

**Comment by zlocate** [comment]
**Нужно исправить** в случае если при создании карточки не все поля заполнены корректно (происходит ошибка валидации) сервис возвращает 500ю ошибку вместо 400й.

**Comment by zlocate** [comment]
> > **Нужно исправить** в случае если в метод регистрации переданы не все поля, например отсутствует поле password сервис падает в 500ю вместо корректной ValidationError с кодом 400
> 
> Денис а здесь можешь пояснить, ведь мы же в схеме для монго пишем что все поля обязательны, я просто не могу понять где ее лучше отловить, в контроллере создания пользователя по err.name? или как?

Тут есть 2 подхода - 
1й - в целом лучше ловить и обрабатывать ошибку максимально близко к месту ее возникновения. 
2- ловить общие ошибки в централизованной мидлваре.

За редким исключением делать доп. логику в мидлваре централизованной обработке не стоит и лучше разруливать ошибки в месте их возникновения. Ведь в одном случае при ошибке валидации мы просто вернем ошибку, а в другом сделаем еще какие-то дополнительные внутренние действия (например что-то запишем в БД, заблокируем злодея-юзера или т.п)

Но это больше про реальные проекту, в рамках учебного вам вероятно удобнее будет ловить err.name или insrtanceOf прямо в централизованном хэндлере

**Comment by zlocate** [comment]
В вашем случае есть уже неплохая заготовка кастомная ошибка BadRequestError

**Comment by zlocate** [comment]
```
    if (!id) {
      return next(new BadRequestError('This id is not valid')); // здесь проверка, не удалена ли уже карточка
    }
```
В данном случае это просто проверка на то, передан ли айдишник, а не на то, существует ли карточка (строго говоря здесь даже нет гарантии что айдишник корректен а не какой-нибудь bla-bla)
И даже корректен ли айдишник

**Comment by zlocate** [comment]
В общем там
1) Комментарий не отражает суть кода
2) Проверка покрывает лишь незначительную часть кейсов.

**Comment by zlocate** [comment]
Строго говоря в это условие мы никогда не попадем, поскольку у express объявлен маршрут с обязательным идентификатором, соответственно если выполняется данный контроллер значит какой-то айдишник все же передали.
Попробуйте вызвать метод delete без ID :) и убедитесь в этом

**Comment by zlocate** [comment]
**Вопрос** нужен ли в ответе удаления карточки populate по полю лайков. Представим что у нас 900 лайков, так вот в массиве у нас будет 900 пользователей со всеми их полями. Это перебор :)

**Comment by zlocate** [comment]
**Нужно исправить** в случае если у нас нет прав на удаления карточки сервис возвращает ошибку 500ю хотя внутри падает правильная Forbidden. Что-то мне подсказывает что место имеет быть имя поля со статус-кодом ошибки.
UPD: Именно оно

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** в случае если у нас нет прав на удаления карточки сервис возвращает ошибку 500ю хотя внутри падает правильная Forbidden. Что-то мне подсказывает что место имеет быть имя поля со статус-кодом ошибки.
> UPD: Именно оно

Есть!

**Comment by zlocate** [comment]
**Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400

В частности если вместо ID пользователя передать 5edfabc8ff3b013f303929a то получим 500ю

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400
> 
> В частности если вместо ID пользователя передать 5edfabc8ff3b013f303929a то получим 500ю

Вот здесь не понимаю, как проверить=(

**Comment by zlocate** [comment]
> > **Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400
> > В частности если вместо ID пользователя передать 5edfabc8ff3b013f303929a то получим 500ю
> 
> Вот здесь не понимаю, как проверить=(

Процитирую себя

**Нужно исправить** если в методы, получающие ID на вход передано некорректное значение например bla-bla-bla, следует возвращать ошибку со статус-кодом 400 (ошибка валидации)
Фактически же внутри ее можно поймать как CastError. (err.name='CastError')

Строго говоря эта ошибка может означать не только ошибку приведение строки к ID но пока мы допустим что это так.

Еще можно проверять на валидность "по форме" ObjectId при помощи встроенного монгусовскоого метода, емнип это mongoose.Types.ObjectId.isValid(id)
Могу на память наврать, но направление мысли думаю ясно.


TLDR; Ловим по err.name == 'CastError' или проверяем `mongoose.Types.ObjectId.isValid(id)`

**Comment by zlocate** [comment]
На правах оффтопа - на досуге посмотрите о новом взгляде на Node.js под названием Deno :)
Штука очень спорная, но любопытная.

**Comment by zlocate** [comment]
На текущий момент отправляю на доработку. По причине 500й на CastError.
Как поправите - отправляйте работу через ЛК практикума, постараюсь оперативно подхватить.

**Comment by zlocate** [comment]
**Нужно исправить** удаление карточки по некорректному по форме ID (CastError) приводит к 500й ошибке вместо 400й
http://i.imgur.com/EFDZKlv.png

**Comment by Atm0Sphere94** [comment]
> **Нужно исправить** удаление карточки по некорректному по форме ID (CastError) приводит к 500й ошибке вместо 400й
> http://i.imgur.com/EFDZKlv.png

Убираю монгусовский метод - просто err.name - cast error

**Comment by zlocate** [comment]
Метод mongoose.Types.ObjectId.isValid(id) возвращает true \ false является ли переданный id корректным по форме id. 
Ошибка CastError не является его инстансом (вариант до этого был корректен)

**Comment by zlocate** [comment]
Я задачу пока не возвращаю, буду посматривать за ишью. Как заремонтируете - тегните меня, гляну.

**Comment by Atm0Sphere94** [comment]
https://yadi.sk/i/mkHc2RlU6LyuBQ

**Comment by Atm0Sphere94** [comment]
https://yadi.sk/i/1q6IqHCXkve55Q

**Comment by Atm0Sphere94** [comment]
@zlocate Денис, оффтоп конечно, а есть шанс выбрать ревьювера на Диплом?!=)))))

**Comment by zlocate** [comment]
@Atm0Sphere94 **нужно исправить** все хорошо, кроме одного, после того как мы пробросили ошибку в next() выполннение не остановилось из-за чего мы имеем в консоли следующее.
http://i.imgur.com/OGPHVw8.png

**Comment by zlocate** [comment]
> @zlocate Денис, оффтоп конечно, а есть шанс выбрать ревьювера на Диплом?!=)))))

Насколько мне известно такой возможности нет (да и фактор субъективности на дипломном проекте стараются минимизировать).

**Comment by Atm0Sphere94** [comment]
> @Atm0Sphere94 **нужно исправить** все хорошо, кроме одного, после того как мы пробросили ошибку в next() выполннение не остановилось из-за чего мы имеем в консоли следующее.
> http://i.imgur.com/OGPHVw8.png

@zlocate Добавил обертку - вроде консоль не ругается

**Comment by zlocate** [comment]
Работа принята. Желаю успехов в следующем спринте и на дипломной работе.

З.Ы Можно было вылечить returnом :)

**Comment by Atm0Sphere94** [comment]
> Работа принята. Желаю успехов на дипломной работе и интересных проектов в дальнейшем.
> 
> З.Ы Можно было вылечить returnом :)
АААА - не убегай=) Апшипка вылезала не раз - подскажи

**Comment by zlocate** [comment]
> > Работа принята. Желаю успехов на дипломной работе и интересных проектов в дальнейшем.
> > З.Ы Можно было вылечить returnом :)
> > АААА - не убегай=) Апшипка вылезала не раз - подскажи

Подаскажите, пожалуйста, о какой ошибке речь

**Comment by Atm0Sphere94** [comment]
Expected to return a value at the end of async arrow function.

**Comment by zlocate** [comment]
А, речь идет об ошибке линтера. 
Смотрите в чем суть - асинхронная функция должна по-уму возвращать какой-либо результат всегда.
Соответственно проследите чтобы у вас во всех ветках асинхронной функции был возврат значения при помощи return

**Comment by zlocate** [comment]
Удачного дня. Надеюсь, еще увидимся :)
